# Default container image to use in pod spec
image: maxwang/appsim:latest

services:
  - name: ui
    type: ClusterIP
    externalPort: 8082
    internalPort: 8082
    talkTo: api
    controller: ReplicationController
    pod:
      count: 1
      name: ui
      label: pod-ui
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0.1
        memory: 10
      rps: 0.1
  - name: api
    type: ClusterIP
    externalPort: 8082
    internalPort: 8082
    talkTo: ui
    # TODO: Use yaml list
    svcListToQuery: book,review
    controller: ReplicationController
    pod:
      count: 1
      name: api
      label: pod-api
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0
        memory: 0
      rps: 0
  - name: book
    type: ClusterIP
    externalPort: 8099
    internalPort: 8099
    talkTo: review
    svcListToQuery: ""
    controller: Deployment
    pod:
      count: 1
      name: book
      label: pod-book
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0
        memory: 0
      rps: 0
  - name: review
    type: ClusterIP
    externalPort: 8099
    internalPort: 8099
    talkTo: book
    svcListToQuery: ""
    controller: ReplicaSet
    pod:
      count: 1
      name: review
      label: pod-review
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0
        memory: 0
      rps: 0
quota:
  enabled: false
  limits:
    cpu: 2
    memory: 2Gi
