# Default container image to use in pod spec
image: maxwang/max-stress-app:latest

services:
  - name: s1-rc
    type: ClusterIP
    externalPort: 8082
    internalPort: 8082
    talkTo: s2-dp
    controller: ReplicationController
    pod:
      count: 1
      name: s1-rc
      label: pod-frontend
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0.99
        memory: 50
      rps: 1.0
  - name: s2-dp
    type: ClusterIP
    externalPort: 8099
    internalPort: 8099
    talkTo: s1-rc
    controller: Deployment
    pod:
      count: 1
      name: s2-dp
      label: pod-backend
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0.1
        memory: 32
      rps: 1.0
  - name: s3-rs
    type: ClusterIP
    externalPort: 8099
    internalPort: 8099
    talkTo: s1-rc
    controller: ReplicaSet
    pod:
      count: 1
      name: s3-rs
      label: pod-s3-rs
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
      usage:
        cpu: 0.99
        memory: 50
      rps: 1.0
quota:
  enabled: false
  limits:
    cpu: 2
    memory: 2Gi
