services:
  - name: max-test-frontend
    type: ClusterIP
    externalPort: 8082
    internalPort: 8082
    talkTo: max-test-backend
    pod:
      count: 2
      name: max-test-frontend
      label: pod-frontend
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
      usage:
        cpu: 0.3
        memory: 64Mi
      rps: 0.5
      image:
        repository: maxwang/max-stress-app
        tag: latest
        pullPolicy: IfNotPresent
  - name: max-test-backend
    type: ClusterIP
    externalPort: 8099
    internalPort: 8099
    talkTo: max-test-frontend
    pod:
      count: 2
      name: max-test-backend
      label: pod-backend
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
      usage:
        cpu: 0.5
        memory: 32Mi
      rps: 1.0
      image:
        repository: maxwang/max-stress-app
        tag: latest
        pullPolicy: IfNotPresent
quota:
  enabled: false
  limits:
    cpu: 2
    memory: 2Gi
