{{- if .Values.quota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    limits.cpu: {{ .Values.quota.limits.cpu }}
    limits.memory: {{ .Values.quota.limits.memory }}
{{- end -}}
